# Generated by Django 2.2 on 2019-04-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20190424_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userinfo',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
    ]
