# Generated by Django 2.2 on 2019-04-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20190424_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='T_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
