# Generated by Django 2.2 on 2019-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20190424_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_article',
            name='a_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_article',
            name='a_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
