# Generated by Django 2.2 on 2019-04-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20190424_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_article',
            name='a_id',
        ),
        migrations.RemoveField(
            model_name='t_article',
            name='a_id',
        ),
    ]
