# Generated by Django 2.2 on 2019-04-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20190424_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_article',
            name='a_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_article',
            name='a_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
