# Generated by Django 2.2 on 2019-04-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_e_article_a_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
