# Generated by Django 2.2 on 2019-04-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190424_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_article',
            name='t_id',
        ),
        migrations.AddField(
            model_name='e_article',
            name='s_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_article',
            name='s_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
